package fr.iut2.sil4.data;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.torque.Column;
import org.apache.torque.TorqueException;
import org.apache.torque.criteria.CriteriaInterface;
import org.apache.torque.om.mapper.RecordMapper;


/**
 * Maps ResultSet rows into Absence objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 20 16:44:53 CET 2014]
 *
 */
public class BaseAbsenceRecordMapper implements RecordMapper<Absence>
{

    /** The class log. */
    private static Log log
            = LogFactory.getLog(BaseAbsenceRecordMapper.class);

    /**
     * Constructs the object from the current row in the resultSet.
     *
     * @param resultSet the resultSet to operate on, already pointing
     *        to the correct row. Not null.
     * @param a possible offset in the columns to be considered
     *        (if previous columns contain other objects),
     *        or 0 for no offset.
     * @param criteria The criteria which created the result set.
     *        If set, the attributes to set in the data object
     *        are determined from the select columns in the criteria;
     *        if no matching column can be found, null is returned.
     *        If not set, all of the table's columns are read from the
     *        result set in the order defined in the table definition.
     *
     * @return the mapped object, not null.
     *
     * @throws TorqueException when reading fields from the RecordSet fails
     *         or if a Criteria is passed which contains select columns other
     *         than the columns in the absence table.
     */
    public Absence processRow(
                ResultSet resultSet,
                int offset,
                CriteriaInterface<?> criteria)
            throws TorqueException
    {
        Absence absence = new Absence();

        try 
        {
            absence.setLoading(true);
            if (criteria == null)
            {
                absence.setAbsenceId(
                        getAbsenceId(resultSet, offset + 1));
                absence.setEtudiantId(
                        getEtudiantId(resultSet, offset + 2));
                absence.setDate(
                        getDate(resultSet, offset + 3));
                absence.setJustifie(
                        getJustifie(resultSet, offset + 4));
            }
            else
            {
                // try to get columns to be mapped
                // from criteria's select columns
                boolean columnMapped = false;
                int totalOffset = offset + 1;
                List<Column> selectColumns = criteria.getSelectColumns();
                List<Column> columnsWithoutOffset = selectColumns.subList(
                        offset, 
                        selectColumns.size());
                for (Column column : columnsWithoutOffset)
                {
                    if (BaseAbsencePeer.ABSENCE_ID.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        absence.setAbsenceId(
                            getAbsenceId(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    else if (BaseAbsencePeer.ETUDIANT_ID.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        absence.setEtudiantId(
                            getEtudiantId(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    else if (BaseAbsencePeer.DATE.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        absence.setDate(
                            getDate(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    else if (BaseAbsencePeer.JUSTIFIE.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        absence.setJustifie(
                            getJustifie(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    totalOffset++;
                }
                if (!columnMapped)
                {
                    log.debug("no columns to map found in criteria, "
                        + "returning null");
                    return null;
                }
            }
            absence.setNew(false);
            absence.setModified(false);
        }
        finally
        {
            absence.setLoading(false);
        }
        return absence;
    }

        /**
         * Reads the value of the <code>columnIndex</code>'th column
         * in the <code>resultSet</code> so that it can be used to set
         * the field absenceId in Absence.
         *
         * @param dbObject the database object to fill, not null.
         * @param resultSet the ResultSet to read from, not null.
         * @param columnIndex the index in the resultSet which should be read.
         *
         * @return the content of the column.
         *
         * @throws SQLException if a problem occurs when reading
         *         from the resultSet.
         */
        protected int getAbsenceId(
                    ResultSet resultSet,
                    int columnIndex)
                throws TorqueException
        {
            try
            {
                return resultSet.getInt(columnIndex);
            }
            catch (SQLException e)
            {
                throw new TorqueException(e);
            }
        }

        /**
         * Reads the value of the <code>columnIndex</code>'th column
         * in the <code>resultSet</code> so that it can be used to set
         * the field etudiantId in Absence.
         *
         * @param dbObject the database object to fill, not null.
         * @param resultSet the ResultSet to read from, not null.
         * @param columnIndex the index in the resultSet which should be read.
         *
         * @return the content of the column.
         *
         * @throws SQLException if a problem occurs when reading
         *         from the resultSet.
         */
        protected int getEtudiantId(
                    ResultSet resultSet,
                    int columnIndex)
                throws TorqueException
        {
            try
            {
                return resultSet.getInt(columnIndex);
            }
            catch (SQLException e)
            {
                throw new TorqueException(e);
            }
        }

        /**
         * Reads the value of the <code>columnIndex</code>'th column
         * in the <code>resultSet</code> so that it can be used to set
         * the field date in Absence.
         *
         * @param dbObject the database object to fill, not null.
         * @param resultSet the ResultSet to read from, not null.
         * @param columnIndex the index in the resultSet which should be read.
         *
         * @return the content of the column.
         *
         * @throws SQLException if a problem occurs when reading
         *         from the resultSet.
         */
        protected java.util.Date getDate(
                    ResultSet resultSet,
                    int columnIndex)
                throws TorqueException
        {
            try
            {
                java.util.Date value = resultSet.getDate(columnIndex);
                if (resultSet.wasNull())
                {
                    value = null;
                }
                return value;
            }
            catch (SQLException e)
            {
                throw new TorqueException(e);
            }
        }

        /**
         * Reads the value of the <code>columnIndex</code>'th column
         * in the <code>resultSet</code> so that it can be used to set
         * the field justifie in Absence.
         *
         * @param dbObject the database object to fill, not null.
         * @param resultSet the ResultSet to read from, not null.
         * @param columnIndex the index in the resultSet which should be read.
         *
         * @return the content of the column.
         *
         * @throws SQLException if a problem occurs when reading
         *         from the resultSet.
         */
        protected boolean getJustifie(
                    ResultSet resultSet,
                    int columnIndex)
                throws TorqueException
        {
            try
            {
                String stringValue = resultSet.getString(columnIndex);
                if ("Y".equals(stringValue))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (SQLException e)
            {
                throw new TorqueException(e);
            }
        }


}
