package fr.iut2.sil4.data;

import java.io.Serializable;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.BooleanKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.om.ColumnAccessByName;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.util.Transaction;
import org.apache.commons.lang.ObjectUtils;


/**
 * Table des etudiants
 *
 * This class was autogenerated by Torque on:
 *
 * [Mon Jan 20 16:44:51 CET 2014]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to Etudiant
 */
public abstract class BaseEtudiant 
    implements Persistent, Serializable, ColumnAccessByName
{
    /** Serial version */
    private static final long serialVersionUID = 1390232691676L;



    /** ID Etudiant */
    private int etudiantId = 0;

    /** Nom Etudiant */
    private String nom = null;

    /** Prenom Etudiant */
    private String prenom = null;

    /** Login Etudiant */
    private String login = null;

    /** Password Etudiant */
    private String password = null;

    /** Classe de l'etudiant */
    private int classeId = 0;

    /** Whether this object was modified after loading or after last save. */
    private boolean modified = true;

    /** 
     * Whether this object was loaded from the database or already saved 
     * (false) or whether it is not yet in the database(true).
     */
    private boolean isNew = true;

    /** Flag which indicates whether this object is currently saving. */
    private boolean saving = false;

    /** 
     * Flag which indicates whether this object is currently loaded
     * from the database. 
     */
    private boolean loading = false;

    /** 
     * Flag which indicates whether this object was deleted from the database.
     * Note that this flags does not always display the current database state,
     * there is no magical connection between this flag and the database.
     */
    private boolean deleted = false;

    /** Defines the aClasse field. */
    private Classe aClasse = null;



    /** Defines the collNotes field. */
    protected List<Note> collNotes = null;

    /** Defines the collAbsences field. */
    protected List<Absence> collAbsences = null;



    /**
     * Get the value of etudiantId.
     * The field is described as follows: 
     * ID Etudiant
     *
     * @return int
     */
    public int getEtudiantId() 
    {
        
        return etudiantId;
    }

    /**
     * Set the value of etudiantId.
     * The field is described as follows: 
     * ID Etudiant
     *
     * @param v new value
     */
    public void setEtudiantId(int v)
    {
        if (this.etudiantId != v)
        {
            setModified(true);
        }

        this.etudiantId = v;

        // update associated objects in collNotes 
        if (collNotes != null)
        {
            for (int i = 0; i < collNotes.size(); i++)
            {
                ((Note) collNotes.get(i))
                        .setEtudiantId(v);
            }
        }
        // update associated objects in collAbsences 
        if (collAbsences != null)
        {
            for (int i = 0; i < collAbsences.size(); i++)
            {
                ((Absence) collAbsences.get(i))
                        .setEtudiantId(v);
            }
        }

    }
    
    /**
     * Get the value of nom.
     * The field is described as follows: 
     * Nom Etudiant
     *
     * @return String
     */
    public String getNom() 
    {
        
        return nom;
    }

    /**
     * Set the value of nom.
     * The field is described as follows: 
     * Nom Etudiant
     *
     * @param v new value
     */
    public void setNom(String v)
    {
        if (!ObjectUtils.equals(this.nom, v))
        {
            setModified(true);
        }

        this.nom = v;


    }
    
    /**
     * Get the value of prenom.
     * The field is described as follows: 
     * Prenom Etudiant
     *
     * @return String
     */
    public String getPrenom() 
    {
        
        return prenom;
    }

    /**
     * Set the value of prenom.
     * The field is described as follows: 
     * Prenom Etudiant
     *
     * @param v new value
     */
    public void setPrenom(String v)
    {
        if (!ObjectUtils.equals(this.prenom, v))
        {
            setModified(true);
        }

        this.prenom = v;


    }
    
    /**
     * Get the value of login.
     * The field is described as follows: 
     * Login Etudiant
     *
     * @return String
     */
    public String getLogin() 
    {
        
        return login;
    }

    /**
     * Set the value of login.
     * The field is described as follows: 
     * Login Etudiant
     *
     * @param v new value
     */
    public void setLogin(String v)
    {
        if (!ObjectUtils.equals(this.login, v))
        {
            setModified(true);
        }

        this.login = v;


    }
    
    /**
     * Get the value of password.
     * The field is described as follows: 
     * Password Etudiant
     *
     * @return String
     */
    public String getPassword() 
    {
        
        return password;
    }

    /**
     * Set the value of password.
     * The field is described as follows: 
     * Password Etudiant
     *
     * @param v new value
     */
    public void setPassword(String v)
    {
        if (!ObjectUtils.equals(this.password, v))
        {
            setModified(true);
        }

        this.password = v;


    }
    
    /**
     * Get the value of classeId.
     * The field is described as follows: 
     * Classe de l'etudiant
     *
     * @return int
     */
    public int getClasseId() 
    {
        
        return classeId;
    }

    /**
     * Set the value of classeId.
     * The field is described as follows: 
     * Classe de l'etudiant
     *
     * @param v new value
     */
    public void setClasseId(int v)
    {
        if (this.classeId != v)
        {
            setModified(true);
        }

        this.classeId = v;
        if (aClasse != null && aClasse.getClasseId() != v)
        {
            aClasse = null;
        }


    }
    

    /**
     * Returns whether the object has ever been saved.  This will
     * be false, if the object was retrieved from storage or was created
     * and then saved.
     *
     * @return true, if the object has never been persisted.
     */
    public boolean isNew()
    {
        return isNew;
    }

    /**
     * Sets whether the object has ever been saved.
     *
     * @param isNew true if the object has never been saved, false otherwise.
     */
    public void setNew(boolean isNew)
    {
        this.isNew = isNew;
    }

    /**
     * Returns whether the object has been modified.
     *
     * @return True if the object has been modified.
     */
    public boolean isModified()
    {
        return modified;
    }

    /**
     * Sets whether the object has been modified.
     *
     * @param modified true if the object has been modified, false otherwise.
     */
    public void setModified(boolean modified)
    {
        this.modified = modified;
    }

    /**
     * Sets the modified state for the object to be false.
     */
    public void resetModified()
    {
        modified = false;
    }


    /**
     * Returns whether this object is currently saving.
     *
     * @return true if this object is currently saving, false otherwise.
     */
    public boolean isSaving()
    {
        return saving;
    }

    /**
     * Sets whether this object is currently saving.
     *
     * @param saving true if this object is currently saving, false otherwise.
     */
    public void setSaving(boolean saving)
    {
        this.saving = saving;
    }


    /**
     * Returns whether this object is currently being loaded from the database.
     *
     * @return true if this object is currently loading, false otherwise.
     */
    public boolean isLoading()
    {
        return loading;
    }

    /**
     * Sets whether this object is currently being loaded from the database.
     *
     * @param loading true if this object is currently loading, false otherwise.
     */
    public void setLoading(boolean loading)
    {
        this.loading = loading;
    }


    /**
     * Returns whether this object was deleted from the database.
     * Note that this getter does not automatically reflect database state,
     * it will be set to true by Torque if doDelete() was called with this 
     * object. Bulk deletes and deletes via primary key do not change
     * this flag. Also, if doDelete() was called on an object which does
     * not exist in the database, the deleted flag is set to true even if
     * it was not deleted.
     *
     * @return true if this object was deleted, false otherwise.
     */
    public boolean isDeleted()
    {
        return deleted;
    }

    /**
     * Sets whether this object was deleted from the database.
     *
     * @param deleted true if this object was deleted, false otherwise.
     */
    public void setDeleted(boolean deleted)
    {
        this.deleted = deleted;
    }


    /**
     * Returns the associated Classe object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Classe object
     * @throws TorqueException when reading from the database fails.
     */
    public Classe getClasse()
        throws TorqueException
    {
        if (aClasse == null && this.classeId != 0)
        {
            aClasse = fr.iut2.sil4.data.ClassePeer.retrieveByPK(SimpleKey.keyFor(this.classeId));
        }
        return aClasse;
    }

    /**
     * Return the associated Classe object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Classe object
     * @throws TorqueException
     */
    public Classe getClasse(Connection connection)
        throws TorqueException
    {
        if (aClasse == null && this.classeId != 0)
        {
            aClasse = fr.iut2.sil4.data.ClassePeer.retrieveByPK(SimpleKey.keyFor(this.classeId), connection);
        }
        return aClasse;
    }


    /**
     * Declares an association between this object and a Classe object
     *
     * @param v Classe
     */
    public void setClasse(Classe v)
    {
        if (v == null)
        {
            setClasseId(0);
        }
        else
        {
            setClasseId(v.getClasseId());
        }
        aClasse = v;
    }
    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setClasseKey(ObjectKey key) throws TorqueException
    {
       
        setClasseId(((NumberKey) key).intValue());
     }



    /**
     * Initializes the cache collNotes for referenced objects.
     * This, means, if collNotes is null when this operation is called, it is
     * initialized with an empty collection, otherwise it remains unchanged. 
     *
     * @return the (possibly new) content of the field collNotes, not null.
     */
    public List<Note> initNotes()
    {
        if (collNotes == null)
        {
            collNotes = new ArrayList<Note>();
        }
        return collNotes;
    }

    /**
     * Checks whether the cache collNotes for referenced objects has either been
     * loaded from the database or has been manually initialized.
     */
    public boolean isNotesInitialized()
    {
        return (collNotes != null);
    }


    /**
     * Method called to associate a Note object to this object
     * through the collNotes foreign key attribute.
     * If the associated objects were not retrieved before
     * and this object is not new, the associated objects are retrieved
     * from the database before adding the <code>toAdd</code> object.
     *
     * @param toAdd the object to add to the associated objects, not null.
     *
     * @throws TorqueException if retrieval of the associated objects fails.
     * @throws NullPointerException if toAdd is null.
     */
    public void addNote(Note toAdd)
        throws TorqueException
    {
        toAdd.setEtudiant((Etudiant) this);
        getNotes().add(toAdd);
    }

    /**
     * Method called to associate a Note object to this object
     * through the collNotes foreign key attribute using connection.
     *
     * @param l Note
     * @throws TorqueException
     */
    public void addNote(Note l, Connection con) throws TorqueException
    {
        getNotes(con).add(l);
        l.setEtudiant((Etudiant) this);
    }
    
    /**
     * The criteria used to select the current contents of collNotes
     */
    private Criteria lastNoteCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getNotes(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<Note> getNotes()
        throws TorqueException
    {
        if (collNotes == null)
        {
            collNotes = getNotes(new Criteria());
        }
        return collNotes;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseEtudiant has previously
     * been saved, it will retrieve related collNotes from storage.
     * If this BaseEtudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<Note> getNotes(Criteria criteria) throws TorqueException
    {
        if (collNotes == null)
        {
            if (isNew())
            {
               initNotes();
            }
            else
            {
                criteria.and(fr.iut2.sil4.data.NotePeer.ETUDIANT_ID, getEtudiantId() );
                collNotes = fr.iut2.sil4.data.NotePeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(fr.iut2.sil4.data.NotePeer.ETUDIANT_ID, getEtudiantId() );
                if (lastNoteCriteria == null 
                        || !lastNoteCriteria.equals(criteria))
                {
                    collNotes = fr.iut2.sil4.data.NotePeer.doSelect(criteria);
                }
            }
        }
        lastNoteCriteria = criteria;

        return collNotes;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getNotes(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<Note> getNotes(Connection con) throws TorqueException
    {
        if (collNotes == null)
        {
            collNotes = getNotes(new Criteria(), con);
        }
        return collNotes;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseEtudiant has previously
     * been saved, it will retrieve the related Note Objects 
     * from storage.
     * If this BaseEtudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<Note> getNotes(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collNotes == null)
        {
            if (isNew())
            {
               initNotes();
            }
            else
            {
                criteria.and(fr.iut2.sil4.data.NotePeer.ETUDIANT_ID, getEtudiantId());
                collNotes = fr.iut2.sil4.data.NotePeer.doSelect(criteria, con);
            }
        }
        else
        {
             // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(fr.iut2.sil4.data.NotePeer.ETUDIANT_ID, getEtudiantId());
                if (!lastNoteCriteria.equals(criteria))
                {
                    collNotes = fr.iut2.sil4.data.NotePeer.doSelect(criteria, con);
                }
            }
        }
        lastNoteCriteria = criteria;

        return collNotes;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseEtudiant is new, it will return
     * an empty collection; or if this thisObjectClassName has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<Note> getNotesJoinEtudiant(Criteria criteria) throws TorqueException
    {
        return getNotesJoinEtudiant(criteria, null);
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseEtudiant is new, it will return
     * an empty collection; or if this BaseEtudiant has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<Note> getNotesJoinEtudiant(Criteria criteria, Connection connection)
        throws TorqueException
    {
        if (collNotes == null)
        {
            if (isNew())
            {
                initNotes();
            }
            else
            {
                criteria.and(fr.iut2.sil4.data.NotePeer.ETUDIANT_ID, getEtudiantId() );
                collNotes = fr.iut2.sil4.data.NotePeer.doSelectJoinEtudiant(criteria, connection);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.and(fr.iut2.sil4.data.NotePeer.ETUDIANT_ID, getEtudiantId() );
            if (!lastNoteCriteria.equals(criteria))
            {
                collNotes = fr.iut2.sil4.data.NotePeer.doSelectJoinEtudiant(criteria, connection);
            }
        }
        lastNoteCriteria = criteria;

        return collNotes;
    }

    /**
     * Initializes the cache collAbsences for referenced objects.
     * This, means, if collAbsences is null when this operation is called, it is
     * initialized with an empty collection, otherwise it remains unchanged. 
     *
     * @return the (possibly new) content of the field collAbsences, not null.
     */
    public List<Absence> initAbsences()
    {
        if (collAbsences == null)
        {
            collAbsences = new ArrayList<Absence>();
        }
        return collAbsences;
    }

    /**
     * Checks whether the cache collAbsences for referenced objects has either been
     * loaded from the database or has been manually initialized.
     */
    public boolean isAbsencesInitialized()
    {
        return (collAbsences != null);
    }


    /**
     * Method called to associate a Absence object to this object
     * through the collAbsences foreign key attribute.
     * If the associated objects were not retrieved before
     * and this object is not new, the associated objects are retrieved
     * from the database before adding the <code>toAdd</code> object.
     *
     * @param toAdd the object to add to the associated objects, not null.
     *
     * @throws TorqueException if retrieval of the associated objects fails.
     * @throws NullPointerException if toAdd is null.
     */
    public void addAbsence(Absence toAdd)
        throws TorqueException
    {
        toAdd.setEtudiant((Etudiant) this);
        getAbsences().add(toAdd);
    }

    /**
     * Method called to associate a Absence object to this object
     * through the collAbsences foreign key attribute using connection.
     *
     * @param l Absence
     * @throws TorqueException
     */
    public void addAbsence(Absence l, Connection con) throws TorqueException
    {
        getAbsences(con).add(l);
        l.setEtudiant((Etudiant) this);
    }
    
    /**
     * The criteria used to select the current contents of collAbsences
     */
    private Criteria lastAbsenceCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getAbsences(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<Absence> getAbsences()
        throws TorqueException
    {
        if (collAbsences == null)
        {
            collAbsences = getAbsences(new Criteria());
        }
        return collAbsences;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseEtudiant has previously
     * been saved, it will retrieve related collAbsences from storage.
     * If this BaseEtudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<Absence> getAbsences(Criteria criteria) throws TorqueException
    {
        if (collAbsences == null)
        {
            if (isNew())
            {
               initAbsences();
            }
            else
            {
                criteria.and(fr.iut2.sil4.data.AbsencePeer.ETUDIANT_ID, getEtudiantId() );
                collAbsences = fr.iut2.sil4.data.AbsencePeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(fr.iut2.sil4.data.AbsencePeer.ETUDIANT_ID, getEtudiantId() );
                if (lastAbsenceCriteria == null 
                        || !lastAbsenceCriteria.equals(criteria))
                {
                    collAbsences = fr.iut2.sil4.data.AbsencePeer.doSelect(criteria);
                }
            }
        }
        lastAbsenceCriteria = criteria;

        return collAbsences;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getAbsences(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<Absence> getAbsences(Connection con) throws TorqueException
    {
        if (collAbsences == null)
        {
            collAbsences = getAbsences(new Criteria(), con);
        }
        return collAbsences;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseEtudiant has previously
     * been saved, it will retrieve the related Absence Objects 
     * from storage.
     * If this BaseEtudiant is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<Absence> getAbsences(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collAbsences == null)
        {
            if (isNew())
            {
               initAbsences();
            }
            else
            {
                criteria.and(fr.iut2.sil4.data.AbsencePeer.ETUDIANT_ID, getEtudiantId());
                collAbsences = fr.iut2.sil4.data.AbsencePeer.doSelect(criteria, con);
            }
        }
        else
        {
             // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(fr.iut2.sil4.data.AbsencePeer.ETUDIANT_ID, getEtudiantId());
                if (!lastAbsenceCriteria.equals(criteria))
                {
                    collAbsences = fr.iut2.sil4.data.AbsencePeer.doSelect(criteria, con);
                }
            }
        }
        lastAbsenceCriteria = criteria;

        return collAbsences;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseEtudiant is new, it will return
     * an empty collection; or if this thisObjectClassName has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<Absence> getAbsencesJoinEtudiant(Criteria criteria) throws TorqueException
    {
        return getAbsencesJoinEtudiant(criteria, null);
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseEtudiant is new, it will return
     * an empty collection; or if this BaseEtudiant has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<Absence> getAbsencesJoinEtudiant(Criteria criteria, Connection connection)
        throws TorqueException
    {
        if (collAbsences == null)
        {
            if (isNew())
            {
                initAbsences();
            }
            else
            {
                criteria.and(fr.iut2.sil4.data.AbsencePeer.ETUDIANT_ID, getEtudiantId() );
                collAbsences = fr.iut2.sil4.data.AbsencePeer.doSelectJoinEtudiant(criteria, connection);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.and(fr.iut2.sil4.data.AbsencePeer.ETUDIANT_ID, getEtudiantId() );
            if (!lastAbsenceCriteria.equals(criteria))
            {
                collAbsences = fr.iut2.sil4.data.AbsencePeer.doSelectJoinEtudiant(criteria, connection);
            }
        }
        lastAbsenceCriteria = criteria;

        return collAbsences;
    }




    private static final List<String> FIELD_NAMES;

    static
    {
        List<String> fieldNames
                = new ArrayList<String>();
        fieldNames.add("EtudiantId");
        fieldNames.add("Nom");
        fieldNames.add("Prenom");
        fieldNames.add("Login");
        fieldNames.add("Password");
        fieldNames.add("ClasseId");
        FIELD_NAMES = Collections.unmodifiableList(fieldNames);
    }

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static List<String> getFieldNames()
    {
        return FIELD_NAMES;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("EtudiantId"))
        {
            return new Integer(getEtudiantId());
        }
        if (name.equals("Nom"))
        {
            return getNom();
        }
        if (name.equals("Prenom"))
        {
            return getPrenom();
        }
        if (name.equals("Login"))
        {
            return getLogin();
        }
        if (name.equals("Password"))
        {
            return getPassword();
        }
        if (name.equals("ClasseId"))
        {
            return new Integer(getClasseId());
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("EtudiantId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setEtudiantId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Nom"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setNom((String) value);
            return true;
        }
        if (name.equals("Prenom"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setPrenom((String) value);
            return true;
        }
        if (name.equals("Login"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setLogin((String) value);
            return true;
        }
        if (name.equals("Password"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setPassword((String) value);
            return true;
        }
        if (name.equals("ClasseId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setClasseId(((Integer) value).intValue());
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(fr.iut2.sil4.data.EtudiantPeer.ETUDIANT_ID))
        {
            return new Integer(getEtudiantId());
        }
        if (name.equals(fr.iut2.sil4.data.EtudiantPeer.NOM))
        {
            return getNom();
        }
        if (name.equals(fr.iut2.sil4.data.EtudiantPeer.PRENOM))
        {
            return getPrenom();
        }
        if (name.equals(fr.iut2.sil4.data.EtudiantPeer.LOGIN))
        {
            return getLogin();
        }
        if (name.equals(fr.iut2.sil4.data.EtudiantPeer.PASSWORD))
        {
            return getPassword();
        }
        if (name.equals(fr.iut2.sil4.data.EtudiantPeer.CLASSE_ID))
        {
            return new Integer(getClasseId());
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (fr.iut2.sil4.data.EtudiantPeer.ETUDIANT_ID.getSqlExpression().equals(name))
        {
            return setByName("EtudiantId", value);
        }
        if (fr.iut2.sil4.data.EtudiantPeer.NOM.getSqlExpression().equals(name))
        {
            return setByName("Nom", value);
        }
        if (fr.iut2.sil4.data.EtudiantPeer.PRENOM.getSqlExpression().equals(name))
        {
            return setByName("Prenom", value);
        }
        if (fr.iut2.sil4.data.EtudiantPeer.LOGIN.getSqlExpression().equals(name))
        {
            return setByName("Login", value);
        }
        if (fr.iut2.sil4.data.EtudiantPeer.PASSWORD.getSqlExpression().equals(name))
        {
            return setByName("Password", value);
        }
        if (fr.iut2.sil4.data.EtudiantPeer.CLASSE_ID.getSqlExpression().equals(name))
        {
            return setByName("ClasseId", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getEtudiantId());
        }
        if (pos == 1)
        {
            return getNom();
        }
        if (pos == 2)
        {
            return getPrenom();
        }
        if (pos == 3)
        {
            return getLogin();
        }
        if (pos == 4)
        {
            return getPassword();
        }
        if (pos == 5)
        {
            return new Integer(getClasseId());
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (position == 0)
        {
            return setByName("EtudiantId", value);
        }
        if (position == 1)
        {
            return setByName("Nom", value);
        }
        if (position == 2)
        {
            return setByName("Prenom", value);
        }
        if (position == 3)
        {
            return setByName("Login", value);
        }
        if (position == 4)
        {
            return setByName("Password", value);
        }
        if (position == 5)
        {
            return setByName("ClasseId", value);
        }
        return false;
    }



    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @param toSave the object to be saved, not null.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save() throws TorqueException
    {
        save(EtudiantPeer.DATABASE_NAME);
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @param toSave the object to be saved, not null.
     * @param dbName the name of the database to which the object
     *        should be saved.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(String dbName) 
            throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally.
     *
     * @param toSave the object to be saved, not null.
     * @param con the connection to use for saving the object, not null.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(Connection con) 
            throws TorqueException
    {
        if (isSaving())
        {
            return;
        }
        try
        {
            setSaving(true);
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    EtudiantPeer.doInsert((Etudiant) this, con);
                    setNew(false);
                }
                else
                {
                    EtudiantPeer.doUpdate((Etudiant) this, con);
                }
            }

            if (isNotesInitialized())
            {
                for (Note collNotes : getNotes())
                {
                    collNotes.save(con);
                }
            }
            if (isAbsencesInitialized())
            {
                for (Absence collAbsences : getAbsences())
                {
                    collAbsences.save(con);
                }
            }
        }
        finally
        {
            setSaving(false);
        }
    }




    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key etudiantId ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
        setEtudiantId(((NumberKey) key).intValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
        setEtudiantId(Integer.parseInt(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getEtudiantId());
    }


    /**
     * Returns an id that differentiates the referenced Classe object
     * from all other Classe objects.
     *
     * @return an ObjectKey.
     */
    public ObjectKey getForeignKeyForClasse()
    {
        int foreignKey = getClasseId();
        if (foreignKey == 0)
        {
            return SimpleKey.keyFor((Number) null);
        }
        return SimpleKey.keyFor(foreignKey);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Etudiant copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using a connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public Etudiant copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public Etudiant copy(boolean deepcopy) throws TorqueException
    {
        Etudiant etudiant = new Etudiant();

        return copyInto(etudiant, deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public Etudiant copy(boolean deepcopy, Connection con) throws TorqueException
    {
        Etudiant etudiant = new Etudiant();

        return copyInto(etudiant, deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    public Etudiant copyInto(Etudiant copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    public Etudiant copyInto(Etudiant copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected Etudiant copyInto(Etudiant copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setEtudiantId(0);
        copyObj.setNom(nom);
        copyObj.setPrenom(prenom);
        copyObj.setLogin(login);
        copyObj.setPassword(password);
        copyObj.setClasseId(classeId);

        if (deepcopy)
        {
            if (collNotes != null)
            {
                for (int i = 0; i < collNotes.size(); i++)
                {
                    Note obj = collNotes.get(i);
                    copyObj.addNote(obj.copy());
                }
            }
            else
            {
                copyObj.collNotes = null;
            }
            if (collAbsences != null)
            {
                for (int i = 0; i < collAbsences.size(); i++)
                {
                    Absence obj = collAbsences.get(i);
                    copyObj.addAbsence(obj.copy());
                }
            }
            else
            {
                copyObj.collAbsences = null;
            }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    public Etudiant copyInto(Etudiant copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setEtudiantId(0);
        copyObj.setNom(nom);
        copyObj.setPrenom(prenom);
        copyObj.setLogin(login);
        copyObj.setPassword(password);
        copyObj.setClasseId(classeId);

        if (deepcopy)
        {
            for (Note obj : getNotes(con))
            {
                copyObj.addNote(obj.copy());
            }
            for (Absence obj : getAbsences(con))
            {
                copyObj.addAbsence(obj.copy());
            }
        }
        return copyObj;
    }

    /** The Peer class */
    private static final fr.iut2.sil4.data.EtudiantPeer peer
            = new fr.iut2.sil4.data.EtudiantPeer();

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public fr.iut2.sil4.data.EtudiantPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return fr.iut2.sil4.data.EtudiantPeer.getTableMap();
    }



    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Etudiant:\n");
        str.append("etudiantId = ")
           .append(getEtudiantId())
           .append("\n");
        str.append("nom = ")
           .append(getNom())
           .append("\n");
        str.append("prenom = ")
           .append(getPrenom())
           .append("\n");
        str.append("login = ")
           .append(getLogin())
           .append("\n");
        str.append("password = ")
           .append(getPassword())
           .append("\n");
        str.append("classeId = ")
           .append(getClasseId())
           .append("\n");
        return(str.toString());
    }

    /**
     * Compares the primary key of this instance with the key of another.
     *
     * @param toCompare The object to compare to.
     * @return Whether the primary keys are equal and the object have the
     *         same class.
     */
    public boolean equals(Object toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!getClass().equals(toCompare.getClass()))
        {
            return false;
        }
        Etudiant other = (Etudiant) toCompare;
        if (getPrimaryKey() == null || other.getPrimaryKey() == null)
        {
            return false;
        }
        return getPrimaryKey().equals(other.getPrimaryKey());
    }

    /**
     * If the primary key is not <code>null</code>, return the hashcode of the
     * primary key.  Otherwise calls <code>Object.hashCode()</code>.
     *
     * @return an <code>int</code> value
     */
    public int hashCode()
    {
        ObjectKey ok = getPrimaryKey();
        if (ok == null)
        {
            return super.hashCode();
        }

        return ok.hashCode();
    }



    /**
     * Compares the content of this object to another object
     *
     * @param toCompare The object to compare to.
     * @return true if all of the columns in the other object have 
     *         the same value as the objects in this class.
     */
    public boolean valueEquals(Etudiant toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (this.etudiantId != toCompare.getEtudiantId())
        {
            return false;
        }
        if (!ObjectUtils.equals(this.nom, toCompare.getNom()))
        {
            return false;
        }
        if (!ObjectUtils.equals(this.prenom, toCompare.getPrenom()))
        {
            return false;
        }
        if (!ObjectUtils.equals(this.login, toCompare.getLogin()))
        {
            return false;
        }
        if (!ObjectUtils.equals(this.password, toCompare.getPassword()))
        {
            return false;
        }
        if (this.classeId != toCompare.getClasseId())
        {
            return false;
        }
        return true;
    }



}
