package fr.iut2.sil4.data;

/**
 * Table des matieres
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 20 16:44:52 CET 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class MatierePeerImpl
    extends fr.iut2.sil4.data.BaseMatierePeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1390232692782L;



}
