package fr.iut2.sil4.data;


/**
 * Table des matieres suivi par une classe
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 20 16:44:51 CET 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class MatiereClasse
    extends fr.iut2.sil4.data.BaseMatiereClasse
{
    /** Serial version */
    private static final long serialVersionUID = 1390232691532L;



}
