package fr.iut2.sil4.data;

/**
 * Table des matieres suivi par une classe
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 20 16:44:52 CET 2014]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class MatiereClassePeer
    extends fr.iut2.sil4.data.BaseMatiereClassePeer
{

}
